kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
    - docker build -t dashboard-sui .

- name: run
  commands:
    - cd /var/docker/sui
    - docker-compose stop sui-dashboard
    - docker-compose up -d sui-dashboard