version: '3.7'

services:
  sui-dashboard:
    image: dashboard-sui
#    build:
#      context: ./
    container_name: dashboard_rani
    restart: unless-stopped
    ports:
      - 4000:80
    volumes:
      - ./:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      - traefik.http.services.dashboard.loadbalancer.server.port=80
      - traefik.http.routers.dashboard.entryPoints=web-secure
      - traefik.http.routers.dashboard.rule=Host(`dashboard.ranii.pro`)
      - traefik.http.routers.dashboard.tls.certresolver=default
    environment:
      - VIRTUAL_HOST=dashboard.ranii.pro